version: '3.8'

# AWS EC2 version of PetClinic app docker-compose
services:
  petclinic:
    image: petclinic-app:latest
    ports:
      - "8080:8080" # Expose for EC2 security group
    environment:
      SPRING_PROFILES_ACTIVE: mysql
    networks:
      - petclinic-net

networks:
  petclinic-net:
    name: petclinic-net
    driver: bridge 